/*
  Estilos inline, portados tal cual del prototipo.
  Se mantienen en un objeto JS para no cambiar dos cosas a la vez; cuando la app
  crezca conviene pasarlos a CSS de verdad (o CSS modules).
*/
export const styles = {
  page: { minHeight: "100vh", background: "#0d0d0f", color: "#ede6da", fontFamily: "'Georgia', 'Iowan Old Style', serif", paddingBottom: 40 },
  header: { borderBottom: "2px solid #7a1f2b", padding: "24px 16px 18px", background: "linear-gradient(180deg, #17161a 0%, #0d0d0f 100%)" },
  headerInner: { maxWidth: 720, margin: "0 auto" },
  docketMark: { fontFamily: "'Courier New', monospace", fontSize: 11, letterSpacing: 2, color: "#b8963e", marginBottom: 6 },
  title: { fontSize: 28, letterSpacing: 3, margin: 0, color: "#ede6da" },
  subtitle: { fontFamily: "system-ui, sans-serif", fontSize: 13, color: "#9a9490", marginTop: 4 },
  /* Sticky: con 184 tarjetas, al scrollear las pestañas quedaban lejísimos.
     El fondo opaco es necesario o el contenido se transparenta por debajo. */
  tabBar: { display: "flex", maxWidth: 720, margin: "0 auto", borderBottom: "1px solid #2a2830", position: "sticky", top: 0, zIndex: 20, background: "#0d0d0f" },
  tabButton: { flex: 1, padding: "12px 4px", background: "transparent", border: "none", color: "#9a9490", fontFamily: "system-ui, sans-serif", fontSize: 13, cursor: "pointer", borderBottom: "2px solid transparent", whiteSpace: "nowrap" },
  tabButtonActive: { color: "#ede6da", borderBottom: "2px solid #7a1f2b" },
  main: { maxWidth: 720, margin: "0 auto", padding: "20px 16px" },
  loading: { fontFamily: "system-ui, sans-serif", color: "#9a9490" },
  helpText: { fontFamily: "system-ui, sans-serif", fontSize: 14, color: "#b3ada6", marginBottom: 16, lineHeight: 1.5 },
  errorBanner: { background: "#3a1414", border: "1px solid #7a1f2b", padding: 10, borderRadius: 4, fontFamily: "system-ui, sans-serif", fontSize: 13, marginBottom: 12 },
  sinnerBlock: { marginBottom: 22 },
  sinnerHeaderBtn: { width: "100%", boxSizing: "border-box", fontSize: 16, letterSpacing: 1.5, color: "#b8963e", border: "none", borderBottom: "1px solid #2a2830", paddingBottom: 6, marginBottom: 10, textTransform: "uppercase", display: "flex", justifyContent: "space-between", alignItems: "baseline", cursor: "pointer", fontFamily: "'Georgia', serif", textAlign: "left", position: "sticky", top: 46, zIndex: 10, background: "#0d0d0f", paddingTop: 6 },
  flecha: { display: "inline-block", width: 14, color: "#5c5852" },
  sinnerCount: { fontFamily: "'Courier New', monospace", fontSize: 12, color: "#5c5852", letterSpacing: 0 },
  buscador: { width: "100%", boxSizing: "border-box", background: "#17161a", border: "1px solid #2a2830", borderRadius: 6, padding: "9px 12px", color: "#ede6da", fontFamily: "system-ui, sans-serif", fontSize: 13.5, marginBottom: 18 },
  rareza: { color: "#b8963e", fontSize: 11, marginLeft: 6, letterSpacing: 1 },
  aviso: { background: "#241d10", border: "1px solid #6b5220", borderRadius: 4, padding: "10px 12px", fontFamily: "system-ui, sans-serif", fontSize: 12.5, color: "#cdbb92", lineHeight: 1.5, marginBottom: 12 },
  orderItemBanca: { opacity: 0.62, borderStyle: "dashed" },
  bancaTag: { fontFamily: "system-ui, sans-serif", fontSize: 10.5, textTransform: "uppercase", letterSpacing: 1, color: "#8a847e", border: "1px solid #3a3840", borderRadius: 10, padding: "1px 7px", marginLeft: 8 },
  footerLink: { color: "#8a847e" },

  chipRow: { display: "flex", gap: 5, flexWrap: "wrap", marginTop: 5 },
  chip: { fontFamily: "system-ui, sans-serif", fontSize: 10.5, letterSpacing: 0.3, border: "1px solid", borderRadius: 10, padding: "1px 8px", whiteSpace: "nowrap", lineHeight: 1.7 },
  chipVacio: { fontFamily: "system-ui, sans-serif", fontSize: 10.5, color: "#5c5852", border: "1px solid #2a2830", borderRadius: 10, padding: "1px 8px", fontStyle: "italic" },
  chipFaccion: { background: "#17161a", color: "#8a847e", borderColor: "#2f2d36" },
  chipFaccionActiva: { background: "#b8963e", color: "#12111a", borderColor: "#b8963e", fontWeight: 600 },
  filtroRow: { display: "flex", gap: 5, flexWrap: "wrap", marginBottom: 10 },
  barraAcciones: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, marginBottom: 16, flexWrap: "wrap" },
  resultado: { fontFamily: "system-ui, sans-serif", fontSize: 12, color: "#8a847e" },
  botonChico: { background: "#17161a", border: "1px solid #3a3840", borderRadius: 6, color: "#b3ada6", fontFamily: "system-ui, sans-serif", fontSize: 12, padding: "5px 10px", cursor: "pointer" },
  rango: { color: "#b8963e", fontSize: 10.5, marginLeft: 6, letterSpacing: 0.8, fontFamily: "system-ui, sans-serif" },
  boton: { background: "#17161a", border: "1px solid #3a3840", borderRadius: 6, color: "#ede6da", fontFamily: "system-ui, sans-serif", fontSize: 13, padding: "7px 14px", cursor: "pointer" },
  botonPrimario: { background: "#2a1c20", border: "1px solid #7a1f2b", borderRadius: 6, color: "#ede6da", fontFamily: "system-ui, sans-serif", fontSize: 13, padding: "7px 14px", cursor: "pointer" },
  compartir: { background: "#131218", border: "1px solid #2a2830", borderRadius: 6, padding: "10px 12px", marginBottom: 18 },
  compartirTitulo: { fontFamily: "system-ui, sans-serif", fontSize: 13, color: "#b8963e", cursor: "pointer", letterSpacing: 0.5 },
  compartirSub: { fontFamily: "system-ui, sans-serif", fontSize: 12.5, textTransform: "uppercase", letterSpacing: 1, color: "#b8963e", marginTop: 20, marginBottom: 8 },
  compartirBotones: { display: "flex", gap: 8, flexWrap: "wrap", marginTop: 8 },
  codigoCaja: { fontFamily: "'Courier New', monospace", fontSize: 11.5, color: "#b3ada6", background: "#0d0d0f", border: "1px solid #2a2830", borderRadius: 4, padding: "8px 10px", wordBreak: "break-all", lineHeight: 1.45, userSelect: "all" },
  pegarCaja: { width: "100%", boxSizing: "border-box", fontFamily: "'Courier New', monospace", fontSize: 11.5, background: "#0d0d0f", color: "#ede6da", border: "1px solid #2a2830", borderRadius: 4, padding: "8px 10px", marginBottom: 8, resize: "vertical" },
  propuesta: { background: "#1a1620", border: "1px solid #6b5220", borderRadius: 6, padding: "12px 14px", marginBottom: 18, fontFamily: "system-ui, sans-serif", fontSize: 13.5, color: "#e0d6c4", lineHeight: 1.5 },
  bannerVisita: { maxWidth: 720, margin: "0 auto", background: "#1c1a24", border: "1px solid #4a4560", borderLeft: "3px solid #8a7fb0", borderRadius: 4, padding: "10px 14px", marginTop: 12, fontFamily: "system-ui, sans-serif", fontSize: 13, color: "#cfc9dd", lineHeight: 1.5 },
  cardSoloLectura: { cursor: "default", opacity: 0.92 },
  subTabBar: { display: "flex", gap: 8, marginBottom: 16 },
  subTab: { flex: 1, padding: "8px 10px", background: "#17161a", border: "1px solid #2a2830", borderRadius: 6, color: "#9a9490", fontFamily: "system-ui, sans-serif", fontSize: 13.5, cursor: "pointer", display: "flex", justifyContent: "center", alignItems: "baseline", gap: 8 },
  subTabActiva: { color: "#ede6da", borderColor: "#b8963e" },
  subTabCount: { fontFamily: "'Courier New', monospace", fontSize: 11.5, color: "#5c5852" },
  costoRow: { display: "flex", gap: 5, flexWrap: "wrap", marginTop: 6 },
  costoPill: { fontFamily: "system-ui, sans-serif", fontSize: 11, color: "#b3ada6", border: "1px solid #2a2830", borderRadius: 10, padding: "1px 8px", background: "#0f0e12" },
  costoPillFalta: { color: "#d08a6a", borderColor: "#7a3a24" },
  egoOk: { fontFamily: "system-ui, sans-serif", fontSize: 11, textTransform: "uppercase", letterSpacing: 0.8, color: "#7aa06a" },
  egoFalta: { fontFamily: "system-ui, sans-serif", fontSize: 11, textTransform: "uppercase", letterSpacing: 0.8, color: "#a86a52" },
  egoNoAlcanza: { opacity: 0.62 },
  sinDatos: { fontFamily: "system-ui, sans-serif", fontSize: 10, textTransform: "uppercase", letterSpacing: 0.8, color: "#a8823c", border: "1px solid #6b5220", borderRadius: 10, padding: "1px 6px", marginLeft: 8, verticalAlign: "middle" },
  sinnerVacio: { fontFamily: "system-ui, sans-serif", fontSize: 12.5, color: "#5c5852", fontStyle: "italic", padding: "4px 0 2px" },
  idGrid: { display: "grid", gridTemplateColumns: "1fr", gap: 8 },
  idCard: { display: "flex", gap: 10, alignItems: "flex-start", background: "#17161a", border: "1px solid #2a2830", borderRadius: 6, padding: "10px 12px", cursor: "pointer" },
  idCardOwned: { borderColor: "#4a6b4a" },
  idCardSelected: { borderColor: "#b8963e" },
  checkbox: { marginTop: 3 },
  idName: { fontSize: 14.5, color: "#ede6da" },
  idTags: { fontFamily: "system-ui, sans-serif", fontSize: 12, color: "#8a847e", marginTop: 2 },
  sectionTitle: { fontSize: 16, letterSpacing: 1, color: "#b8963e", marginTop: 28, marginBottom: 10, textTransform: "uppercase", borderBottom: "1px solid #2a2830", paddingBottom: 6 },
  orderList: { listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 8 },
  orderItem: { display: "flex", gap: 12, alignItems: "flex-start", background: "#17161a", border: "1px solid #2a2830", borderRadius: 6, padding: "10px 12px" },
  orderNumber: { fontFamily: "'Courier New', monospace", fontSize: 18, color: "#7a1f2b", minWidth: 22 },
  reasonText: { fontFamily: "system-ui, sans-serif", fontSize: 12.5, color: "#b3ada6", marginTop: 2, lineHeight: 1.4 },
  resRow: { display: "flex", gap: 8, flexWrap: "wrap" },
  resPill: { fontFamily: "system-ui, sans-serif", fontSize: 12.5, background: "#17161a", border: "1px solid #2a2830", borderRadius: 20, padding: "6px 12px", display: "flex", gap: 6, alignItems: "baseline" },
  resDetalle: { color: "#8a847e", fontSize: 11.5 },
  candidateList: { display: "flex", flexDirection: "column", gap: 10 },
  candidateCard: { background: "#17161a", border: "1px solid #2a2830", borderRadius: 6, padding: "12px 14px" },
  candidateHeader: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  scoreBadge: { fontFamily: "'Courier New', monospace", color: "#b8963e", fontSize: 13 },
  reasonList: { margin: "8px 0 0", paddingLeft: 18 },
  footer: { textAlign: "center", fontFamily: "system-ui, sans-serif", fontSize: 11.5, color: "#5c5852", marginTop: 20, padding: "0 16px" },
};
