/*
  Estilos inline, portados tal cual del prototipo.
  Se mantienen en un objeto JS para no cambiar dos cosas a la vez; cuando la app
  crezca conviene pasarlos a CSS de verdad (o CSS modules).
*/
export const styles = {
  page: { minHeight: "100vh", background: "#0d0d0f", color: "#ede6da", fontFamily: "'Georgia', 'Iowan Old Style', serif", paddingBottom: 40 },
  header: { borderBottom: "2px solid #7a1f2b", padding: "24px 16px 18px", background: "linear-gradient(180deg, #17161a 0%, #0d0d0f 100%)" },
  headerInner: { maxWidth: 720, margin: "0 auto" },
  docketMark: { fontFamily: "'Courier New', monospace", fontSize: 11, letterSpacing: 2, color: "#b8963e", marginBottom: 6 },
  title: { fontSize: 28, letterSpacing: 3, margin: 0, color: "#ede6da" },
  subtitle: { fontFamily: "system-ui, sans-serif", fontSize: 13, color: "#9a9490", marginTop: 4 },
  /* Sticky: con 184 tarjetas, al scrollear las pestañas quedaban lejísimos.
     El fondo opaco es necesario o el contenido se transparenta por debajo. */
  tabBar: { display: "flex", maxWidth: 720, margin: "0 auto", borderBottom: "1px solid #2a2830", position: "sticky", top: 0, zIndex: 20, background: "#0d0d0f" },
  tabButton: { flex: 1, padding: "12px 4px", background: "transparent", border: "none", color: "#9a9490", fontFamily: "system-ui, sans-serif", fontSize: 13, cursor: "pointer", borderBottom: "2px solid transparent", whiteSpace: "nowrap" },
  tabButtonActive: { color: "#ede6da", borderBottom: "2px solid #7a1f2b" },
  main: { maxWidth: 720, margin: "0 auto", padding: "20px 16px" },
  loading: { fontFamily: "system-ui, sans-serif", color: "#9a9490" },
  helpText: { fontFamily: "system-ui, sans-serif", fontSize: 14, color: "#b3ada6", marginBottom: 16, lineHeight: 1.5 },
  errorBanner: { background: "#3a1414", border: "1px solid #7a1f2b", padding: 10, borderRadius: 4, fontFamily: "system-ui, sans-serif", fontSize: 13, marginBottom: 12 },
  sinnerBlock: { marginBottom: 22 },
  sinnerHeaderBtn: { width: "100%", boxSizing: "border-box", fontSize: 16, letterSpacing: 1.5, color: "#b8963e", border: "none", borderBottom: "1px solid #2a2830", paddingBottom: 6, marginBottom: 10, textTransform: "uppercase", display: "flex", justifyContent: "space-between", alignItems: "baseline", cursor: "pointer", fontFamily: "'Georgia', serif", textAlign: "left", position: "sticky", top: 46, zIndex: 10, background: "#0d0d0f", paddingTop: 6 },
  flecha: { display: "inline-block", width: 14, color: "#5c5852" },
  sinnerCount: { fontFamily: "'Courier New', monospace", fontSize: 12, color: "#5c5852", letterSpacing: 0 },
  buscador: { width: "100%", boxSizing: "border-box", background: "#17161a", border: "1px solid #2a2830", borderRadius: 6, padding: "9px 12px", color: "#ede6da", fontFamily: "system-ui, sans-serif", fontSize: 13.5, marginBottom: 18 },
  rareza: { color: "#b8963e", fontSize: 11, marginLeft: 6, letterSpacing: 1 },
  aviso: { background: "#241d10", border: "1px solid #6b5220", borderRadius: 4, padding: "10px 12px", fontFamily: "system-ui, sans-serif", fontSize: 12.5, color: "#cdbb92", lineHeight: 1.5, marginBottom: 12 },
  orderItemBanca: { opacity: 0.62, borderStyle: "dashed" },
  bancaTag: { fontFamily: "system-ui, sans-serif", fontSize: 10.5, textTransform: "uppercase", letterSpacing: 1, color: "#8a847e", border: "1px solid #3a3840", borderRadius: 10, padding: "1px 7px", marginLeft: 8 },
  footerLink: { color: "#8a847e" },

  retrato: { borderRadius: 5, border: "1px solid #2a2830", background: "#0f0e12", display: "block", flexShrink: 0 },
  retratoVacio: { display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "system-ui, sans-serif", fontWeight: 600, letterSpacing: 0.5, userSelect: "none" },
  chipRow: { display: "flex", gap: 5, flexWrap: "wrap", marginTop: 5 },
  chip: { fontFamily: "system-ui, sans-serif", fontSize: 10.5, letterSpacing: 0.3, border: "1px solid", borderRadius: 10, padding: "1px 8px", whiteSpace: "nowrap", lineHeight: 1.7 },
  chipVacio: { fontFamily: "system-ui, sans-serif", fontSize: 10.5, color: "#5c5852", border: "1px solid #2a2830", borderRadius: 10, padding: "1px 8px", fontStyle: "italic" },
  chipFaccion: { background: "#17161a", color: "#8a847e", borderColor: "#2f2d36" },
  chipFaccionActiva: { background: "#b8963e", color: "#12111a", borderColor: "#b8963e", fontWeight: 600 },
  filtroRow: { display: "flex", gap: 5, flexWrap: "wrap", marginBottom: 10 },
  barraAcciones: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, marginBottom: 16, flexWrap: "wrap" },
  resultado: { fontFamily: "system-ui, sans-serif", fontSize: 12, color: "#8a847e" },
  botonChico: { background: "#17161a", border: "1px solid #3a3840", borderRadius: 6, color: "#b3ada6", fontFamily: "system-ui, sans-serif", fontSize: 12, padding: "5px 10px", cursor: "pointer" },
  rango: { color: "#b8963e", fontSize: 10.5, marginLeft: 6, letterSpacing: 0.8, fontFamily: "system-ui, sans-serif" },
  boton: { background: "#17161a", border: "1px solid #3a3840", borderRadius: 6, color: "#ede6da", fontFamily: "system-ui, sans-serif", fontSize: 13, padding: "7px 14px", cursor: "pointer" },
  botonPrimario: { background: "#2a1c20", border: "1px solid #7a1f2b", borderRadius: 6, color: "#ede6da", fontFamily: "system-ui, sans-serif", fontSize: 13, padding: "7px 14px", cursor: "pointer" },
  compartir: { background: "#131218", border: "1px solid #2a2830", borderRadius: 6, padding: "10px 12px", marginBottom: 18 },
  compartirTitulo: { fontFamily: "system-ui, sans-serif", fontSize: 13, color: "#b8963e", cursor: "pointer", letterSpacing: 0.5 },
  compartirSub: { fontFamily: "system-ui, sans-serif", fontSize: 12.5, textTransform: "uppercase", letterSpacing: 1, color: "#b8963e", marginTop: 20, marginBottom: 8 },
  compartirBotones: { display: "flex", gap: 8, flexWrap: "wrap", marginTop: 8 },
  codigoCaja: { fontFamily: "'Courier New', monospace", fontSize: 11.5, color: "#b3ada6", background: "#0d0d0f", border: "1px solid #2a2830", borderRadius: 4, padding: "8px 10px", wordBreak: "break-all", lineHeight: 1.45, userSelect: "all" },
  pegarCaja: { width: "100%", boxSizing: "border-box", fontFamily: "'Courier New', monospace", fontSize: 11.5, background: "#0d0d0f", color: "#ede6da", border: "1px solid #2a2830", borderRadius: 4, padding: "8px 10px", marginBottom: 8, resize: "vertical" },
  propuesta: { background: "#1a1620", border: "1px solid #6b5220", borderRadius: 6, padding: "12px 14px", marginBottom: 18, fontFamily: "system-ui, sans-serif", fontSize: 13.5, color: "#e0d6c4", lineHeight: 1.5 },
  bannerVisita: { maxWidth: 720, margin: "0 auto", background: "#1c1a24", border: "1px solid #4a4560", borderLeft: "3px solid #8a7fb0", borderRadius: 4, padding: "10px 14px", marginTop: 12, fontFamily: "system-ui, sans-serif", fontSize: 13, color: "#cfc9dd", lineHeight: 1.5 },
  cardSoloLectura: { cursor: "default", opacity: 0.92 },
  subTabBar: { display: "flex", gap: 8, marginBottom: 16 },
  subTab: { flex: 1, padding: "8px 10px", background: "#17161a", border: "1px solid #2a2830", borderRadius: 6, color: "#9a9490", fontFamily: "system-ui, sans-serif", fontSize: 13.5, cursor: "pointer", display: "flex", justifyContent: "center", alignItems: "baseline", gap: 8 },
  subTabActiva: { color: "#ede6da", borderColor: "#b8963e" },
  subTabCount: { fontFamily: "'Courier New', monospace", fontSize: 11.5, color: "#5c5852" },
  costoRow: { display: "flex", gap: 5, flexWrap: "wrap", marginTop: 6 },
  costoPill: { fontFamily: "system-ui, sans-serif", fontSize: 11, color: "#b3ada6", border: "1px solid #2a2830", borderRadius: 10, padding: "1px 8px", background: "#0f0e12" },
  costoPillFalta: { color: "#d08a6a", borderColor: "#7a3a24" },
  egoOk: { fontFamily: "system-ui, sans-serif", fontSize: 11, textTransform: "uppercase", letterSpacing: 0.8, color: "#7aa06a" },
  egoFalta: { fontFamily: "system-ui, sans-serif", fontSize: 11, textTransform: "uppercase", letterSpacing: 0.8, color: "#a86a52" },
  egoNoAlcanza: { opacity: 0.62 },
  parcial: { fontFamily: "system-ui, sans-serif", fontSize: 10, textTransform: "uppercase", letterSpacing: 0.8, color: "#7f8fa8", border: "1px solid #3f4d63", borderRadius: 10, padding: "1px 6px", marginLeft: 8, verticalAlign: "middle" },
  sinDatos: { fontFamily: "system-ui, sans-serif", fontSize: 10, textTransform: "uppercase", letterSpacing: 0.8, color: "#a8823c", border: "1px solid #6b5220", borderRadius: 10, padding: "1px 6px", marginLeft: 8, verticalAlign: "middle" },
  sinnerVacio: { fontFamily: "system-ui, sans-serif", fontSize: 12.5, color: "#5c5852", fontStyle: "italic", padding: "4px 0 2px" },
  idGrid: { display: "grid", gridTemplateColumns: "1fr", gap: 8 },
  idCard: { display: "flex", gap: 10, alignItems: "flex-start", background: "#17161a", border: "1px solid #2a2830", borderRadius: 6, padding: "10px 12px", cursor: "pointer" },
  idCardOwned: { borderColor: "#4a6b4a" },
  idCardSelected: { borderColor: "#b8963e" },
  checkbox: { marginTop: 3 },
  idName: { fontSize: 14.5, color: "#ede6da" },
  idTags: { fontFamily: "system-ui, sans-serif", fontSize: 12, color: "#8a847e", marginTop: 2 },
  sectionTitle: { fontSize: 16, letterSpacing: 1, color: "#b8963e", marginTop: 28, marginBottom: 10, textTransform: "uppercase", borderBottom: "1px solid #2a2830", paddingBottom: 6 },
  orderList: { listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 8 },
  orderItem: { display: "flex", gap: 12, alignItems: "flex-start", background: "#17161a", border: "1px solid #2a2830", borderRadius: 6, padding: "10px 12px" },
  orderNumber: { fontFamily: "'Courier New', monospace", fontSize: 18, color: "#7a1f2b", minWidth: 22 },
  reasonText: { fontFamily: "system-ui, sans-serif", fontSize: 12.5, color: "#b3ada6", marginTop: 2, lineHeight: 1.4 },
  /* El motivo de posición va antes que el de recursos y se distingue: es el
     único de los dos que habla del slot y no de a quién bajar a la cancha. */
  reasonPosicion: { fontFamily: "system-ui, sans-serif", fontSize: 12.5, color: "#d8c9a0", marginTop: 2, lineHeight: 1.4 },
  /* Discreto a propósito: no compite con la casilla, que es la acción principal. */
  botonFicha: { alignSelf: "center", flex: "0 0 auto", fontFamily: "system-ui, sans-serif", fontSize: 10, textTransform: "uppercase", letterSpacing: 0.8, color: "#8d8880", background: "transparent", border: "1px solid #3a3631", borderRadius: 3, padding: "3px 6px", cursor: "pointer" },

  /* --- Qué me falta --- */
  resumenFaltan: { display: "flex", gap: 18, flexWrap: "wrap", padding: "10px 12px", background: "#1b1917", border: "1px solid #2c2926", borderRadius: 6, marginTop: 8 },
  numeroGrande: { fontFamily: "system-ui, sans-serif", fontSize: 26, fontWeight: 700, color: "#e8e3dc", lineHeight: 1.1 },
  numeroChico: { fontSize: 15, fontWeight: 400, color: "#8d8880" },
  barraSinners: { display: "flex", gap: 3, marginTop: 6 },
  barraLlena: { width: 16, height: 6, background: "#c9bfa8", borderRadius: 2 },
  barraVacia: { width: 16, height: 6, background: "#332f2b", borderRadius: 2 },
  avisoOk: { fontFamily: "system-ui, sans-serif", fontSize: 12.5, color: "#a8c9a0", background: "#1a201a", border: "1px solid #2f402c", borderRadius: 4, padding: "8px 10px", marginTop: 8, lineHeight: 1.45 },
  /* La candidata cuyo Sinner ya está cubierto no es mala, pero no agranda el equipo. */
  candidataTibia: { opacity: 0.72 },

  chipRol: { fontFamily: "system-ui, sans-serif", fontSize: 11, color: "#b3ada6", background: "#1b1917", border: "1px solid #3a3631", borderRadius: 11, padding: "3px 9px", cursor: "pointer" },
  chipRolActivo: { color: "#151413", background: "#c9bfa8", borderColor: "#c9bfa8", fontWeight: 600 },
  tituloConAccion: { display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: 10, flexWrap: "wrap" },

  /* --- Ficha y comparador --- */
  overlay: { position: "fixed", inset: 0, background: "rgba(8,7,7,0.78)", display: "flex", alignItems: "flex-start", justifyContent: "center", padding: 12, zIndex: 50, overflowY: "auto" },
  panel: { background: "#151413", border: "1px solid #2c2926", borderRadius: 6, width: "100%", maxWidth: 760, marginBottom: 24 },
  /* La barra queda fija arriba: en una ficha larga, "Cerrar" no puede quedar fuera de pantalla. */
  panelBarra: { position: "sticky", top: 0, display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, padding: "10px 12px", background: "#1b1917", borderBottom: "1px solid #2c2926", borderRadius: "6px 6px 0 0" },
  panelTitulo: { fontFamily: "system-ui, sans-serif", fontSize: 12, textTransform: "uppercase", letterSpacing: 1, color: "#b3ada6" },
  panelCuerpo: { padding: 12 },
  botonChico: { fontFamily: "system-ui, sans-serif", fontSize: 12, color: "#e8e3dc", background: "#26231f", border: "1px solid #3a3631", borderRadius: 4, padding: "5px 10px", cursor: "pointer" },
  selectorComparar: { display: "flex", flexDirection: "column", gap: 3, marginTop: 10 },
  select: { fontFamily: "system-ui, sans-serif", fontSize: 13, color: "#e8e3dc", background: "#1b1917", border: "1px solid #3a3631", borderRadius: 4, padding: "6px 8px", width: "100%", maxWidth: 360 },
  detalleEncabezado: { display: "flex", gap: 10, alignItems: "center", flex: "1 1 240px", minWidth: 0, padding: "6px 8px", background: "#1b1917", borderRadius: 4 },
  detalleSeccion: { marginTop: 14, paddingTop: 12, borderTop: "1px solid #2c2926" },
  detalleTituloId: { fontFamily: "system-ui, sans-serif", fontSize: 13, fontWeight: 600, color: "#e8e3dc", marginBottom: 4 },
  detalleSubtitulo: { fontFamily: "system-ui, sans-serif", fontSize: 11, textTransform: "uppercase", letterSpacing: 0.9, color: "#8d8880", marginBottom: 4 },
  /* Las tablas anchas scrollean solas; el body de la página nunca se mueve de costado. */
  tablaScroll: { overflowX: "auto", marginTop: 8 },
  tabla: { borderCollapse: "collapse", width: "100%", fontFamily: "system-ui, sans-serif", fontSize: 12.5 },
  th: { textAlign: "left", padding: "5px 8px", color: "#8d8880", fontWeight: 600, borderBottom: "1px solid #2c2926", whiteSpace: "nowrap" },
  td: { padding: "5px 8px", color: "#d6d0c8", borderBottom: "1px solid #211f1d", verticalAlign: "top" },
  tdEtiqueta: { color: "#8d8880", whiteSpace: "nowrap" },
  tdDistinto: { background: "#221f1a", color: "#f0e6d2" },
  pasivaBloque: { padding: "6px 8px", background: "#1b1917", borderRadius: 4, marginBottom: 5 },
  pasivaNombre: { fontFamily: "system-ui, sans-serif", fontSize: 13, fontWeight: 600, color: "#e8e3dc" },
  pasivaTexto: { fontFamily: "system-ui, sans-serif", fontSize: 12.5, color: "#c4beb6", lineHeight: 1.45, marginTop: 3, whiteSpace: "pre-wrap" },
  listaSinergia: { listStyle: "none", margin: "8px 0 0", padding: 0, display: "flex", flexDirection: "column", gap: 4 },
  filaSinergia: { display: "flex", alignItems: "baseline", flexWrap: "wrap", gap: 8, padding: "5px 8px", background: "#1b1917", borderRadius: 4, border: "1px solid #2c2926" },
  resRow: { display: "flex", gap: 8, flexWrap: "wrap" },
  resPill: { fontFamily: "system-ui, sans-serif", fontSize: 12.5, background: "#17161a", border: "1px solid #2a2830", borderRadius: 20, padding: "6px 12px", display: "flex", gap: 6, alignItems: "baseline" },
  resDetalle: { color: "#8a847e", fontSize: 11.5 },
  candidateList: { display: "flex", flexDirection: "column", gap: 10 },
  candidateCard: { background: "#17161a", border: "1px solid #2a2830", borderRadius: 6, padding: "12px 14px" },
  candidateHeader: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  scoreBadge: { fontFamily: "'Courier New', monospace", color: "#b8963e", fontSize: 13 },
  reasonList: { margin: "8px 0 0", paddingLeft: 18 },
  footer: { textAlign: "center", fontFamily: "system-ui, sans-serif", fontSize: 11.5, color: "#5c5852", marginTop: 20, padding: "0 16px" },
};
